version: '3.6'
services: 
  redis-server:
    image: 'redis'
  node-app:
    restart: always
    build:
      context: .
    ports:
      - "4001:8081"
    volumes: 
      - /app/node_modules
      - .:/app 